# Using an updated Gitpod docker image (when using a non default JDK or tools)
image:
  file: .gitpod.Dockerfile

tasks:
  - init: sdk default java 11.0.15-tem

vscode:
  extensions:
    - bierner.markdown-preview-github-styles
    - github.vscode-pull-request-github
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
