# https://github.com/oracle/container-images/pkgs/container/oraclelinux
# recommends 8-slim but this image chooses specifically to use 8.6 because
# it is more precise.
FROM ghcr.io/oracle/oraclelinux:8.6
RUN dnf install -y redhat-lsb-core
