# https://github.com/oracle/container-images/pkgs/container/oraclelinux
# recommends 8-slim. It is unfortunate that it does not have a more precise
# version number.
FROM ghcr.io/oracle/oraclelinux:8-slim
RUN microdnf install -y redhat-lsb-core
