# https://github.com/oracle/container-images/pkgs/container/oraclelinux
# recommends 7-slim. It is unfortunate that it does not have a more precise
# version number.
FROM ghcr.io/oracle/oraclelinux:7-slim
RUN yum install -y redhat-lsb-core
